config/routes.rb
Thumbs::Application.routes.draw do
  resources :thumbnails

end

app/models/thumbnail.rb
class Thumbnail < ActiveRecord::Base
  attr_accessible :description, :image, :title, :link, :order_by
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/thumbnails_controller.rb
class ThumbnailsController < ApplicationController
  # GET /thumbnails
  # GET /thumbnails.json
  def index
    @thumbnails = Thumbnail.order("order_by ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @thumbnails }
    end
  end

  # GET /thumbnails/1
  # GET /thumbnails/1.json
  def show
    @thumbnail = Thumbnail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thumbnail }
    end
  end

  # GET /thumbnails/new
  # GET /thumbnails/new.json
  def new
    @thumbnail = Thumbnail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thumbnail }
    end
  end

  # GET /thumbnails/1/edit
  def edit
    @thumbnail = Thumbnail.find(params[:id])
  end

  # POST /thumbnails
  # POST /thumbnails.json
  def create
    @thumbnail = Thumbnail.new(params[:thumbnail])

    respond_to do |format|
      if @thumbnail.save
        format.html { redirect_to @thumbnail, notice: 'Thumbnail was successfully created.' }
        format.json { render json: @thumbnail, status: :created, location: @thumbnail }
      else
        format.html { render action: "new" }
        format.json { render json: @thumbnail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /thumbnails/1
  # PUT /thumbnails/1.json
  def update
    @thumbnail = Thumbnail.find(params[:id])

    respond_to do |format|
      if @thumbnail.update_attributes(params[:thumbnail])
        format.html { redirect_to @thumbnail, notice: 'Thumbnail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @thumbnail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thumbnails/1
  # DELETE /thumbnails/1.json
  def destroy
    @thumbnail = Thumbnail.find(params[:id])
    @thumbnail.destroy

    respond_to do |format|
      format.html { redirect_to thumbnails_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/thumbnails_helper.rb
module ThumbnailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thumbs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/thumbnails/_form.html.erb
<%= form_for(@thumbnail) do |f| %>
  <% if @thumbnail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thumbnail.errors.count, "error") %> prohibited this thumbnail from being saved:</h2>

      <ul>
      <% @thumbnail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div> 
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.text_field :order_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thumbnails/edit.html.erb
<h1>Editing thumbnail</h1>

<%= render 'form' %>

<%= link_to 'Show', @thumbnail %> |
<%= link_to 'Back', thumbnails_path %>

app/views/thumbnails/index.html.erb
<h1>Listing thumbnails</h1>

<table>
  <tr>
    <th>Link</th>
    <th>Image</th>
    <th>Title</th>
    <th>Description</th>
    <th>Order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @thumbnails.each do |thumbnail| %>
  <tr>
    <td><%= thumbnail.link %></td>
    <td><%= thumbnail.image %></td>
    <td><%= thumbnail.title %></td>
    <td><%= thumbnail.description.html_safe %></td>
    <td><%= thumbnail.order_by %></td>
    <td><%= link_to 'Show', thumbnail %></td>
    <td><%= link_to 'Edit', edit_thumbnail_path(thumbnail) %></td>
    <td><%= link_to 'Destroy', thumbnail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Thumbnail', new_thumbnail_path %>

app/views/thumbnails/new.html.erb
<h1>New thumbnail</h1>

<%= render 'form' %>

<%= link_to 'Back', thumbnails_path %>

app/views/thumbnails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= @thumbnail.image %>
</p>
<p>
  <b>Link:</b>
  <%= @thumbnail.link %>
</p>

<p>
  <b>Title:</b>
  <%= @thumbnail.title %>
</p>

<p>
  <b>Description:</b>
  <%= @thumbnail.description %>
</p>

<p>
  <b>Order:</b>
  <%= @thumbnail.order_by %>
</p>


<%= link_to 'Edit', edit_thumbnail_path(@thumbnail) %> |
<%= link_to 'Back', thumbnails_path %>